- name: install golang
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: import pre req
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq.yml

- name: Ensure no old go.mod exists
  ansible.builtin.file:
    path: /dispatch/go.mod
    state: absent

- name: init and build golang
  ansible.builtin.shell: go mod init dispatch;

- name: init and build golang
  ansible.builtin.shell: go get;

- name: init and build golang
  ansible.builtin.shell: go build

- name: import systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml
